# OptimaCX Platform - Base Configuration
application:
  name: "optimacx-platform"
  version: "1.0.0"

database:
  type: "postgresql"
  pool_size: 10
  timeout: 30

n8n:
  user_management_disabled: true
  metrics_enabled: true
  diagnostics_enabled: false

security:
  encryption_algorithm: "AES-256"
  session_timeout: 3600

monitoring:
  logging_level: "INFO"
  metrics_enabled: true