# Development Environment Configuration
extends: "../base.yaml"

environment: "development"

gcp:
  project_id: "burnished-data-463915-d8"
  region: "southamerica-west1"  # Santiago, Chile

database:
  instance_name: "optimacx-dev-postgres"
  database_name: "optimacx_dev"
  machine_type: "db-f1-micro"

cloud_run:
  service_name: "n8n-optimacx-dev"
  memory: "1Gi"
  cpu: "1000m"
  min_instances: 0
  max_instances: 3

monitoring:
  logging_level: "DEBUG"