# Development Environment Configuration
extends: "../base.yaml"

environment: "development"

gcp:
  project_id: "optima-cx-467616"
  region: "southamerica-west1"  # Santiago, Chile

database:
  instance_name: "optimacx-dev-postgres"
  database_name: "optimacx_dev"
  machine_type: "db-f1-micro"

cloud_run:
  service_name: "n8n-optimacx-dev"
  memory: "1Gi"
  cpu: "1000m"
  min_instances: 0
  max_instances: 3

n8n:
  user_management_disabled: true
  metrics_enabled: true
  diagnostics_enabled: true

security:
  session_timeout: 7200

monitoring:
  logging_level: "DEBUG"