# Production Environment Configuration
extends: "../base.yaml"

environment: "production"

gcp:
  project_id: "burnished-data-463915-d8"
  region: "southamerica-west1"  # Santiago, Chile

database:
  instance_name: "optimacx-prod-postgres"
  database_name: "optimacx_prod"
  machine_type: "db-custom-2-4096"
  backup_enabled: true
  backup_retention_days: 30

cloud_run:
  service_name: "n8n-optimacx-prod"
  memory: "2Gi"
  cpu: "2000m"
  min_instances: 1
  max_instances: 10

security:
  session_timeout: 1800

monitoring:
  logging_level: "WARN"